name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: macos-latest
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.9.0"
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-Journey-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-Journey
      - name: Build
        run: xcodebuild -scheme Journey -sdk iphoneos -destination 'platform=iOS Simulator name=iPhone 15 Pro'
